"""
Context Generator – Auto-generates .copyboard-context.md in the project root.

This file is similar to .cursorrules but data-driven: it is generated from
the user's actual Copyboard usage instead of hand-written rules.

AI agents that read project files will pick up this context automatically.
"""

import os
import datetime
from typing import Optional

from .profile_generator import generate_profile, profile_to_markdown
from .snippet_manager import snippets as _default_snippets


def generate_context_file(
    output_dir: Optional[str] = None,
    filename: str = ".copyboard-context.md",
    snippets_mgr=None,
    config_mgr=None,
) -> str:
    """Generate or update the .copyboard-context.md file.

    Args:
        output_dir: Directory to write to (defaults to CWD).
        filename:   Output filename.
        snippets_mgr: SnippetManager instance (defaults to singleton).
        config_mgr:   ConfigManager instance (optional).

    Returns:
        Absolute path to the generated file.
    """
    if snippets_mgr is None:
        snippets_mgr = _default_snippets

    # Check config for filename override and opt-out
    if config_mgr:
        enabled = config_mgr.get("agent", "profile_enabled", True)
        if not enabled:
            return ""
        filename = config_mgr.get("agent", "context_file", filename)

    if output_dir is None:
        output_dir = os.getcwd()

    profile = generate_profile(snippets_mgr, config_mgr)

    # Build a context file with agent-facing instructions
    lines = [
        "<!-- Auto-generated by Copyboard. Do not edit manually. -->",
        "<!-- Regenerate with: copyboard context generate -->",
        "",
    ]
    lines.append(profile_to_markdown(profile))

    lines.extend([
        "",
        "---",
        "",
        "## For AI Agents",
        "",
        "This project uses **Copyboard** for clipboard management and code snippets.",
        "",
        "### Quick Reference",
        "",
        "```bash",
        "# Fire a snippet (copies to clipboard)",
        'copyboard snippet fire <chamber_idx> <snippet_idx>',
        "",
        "# Search for a snippet",
        'copyboard snippet search "keyword"',
        "",
        "# Get coding profile as JSON",
        "copyboard profile --json",
        "",
        "# List all chambers",
        "copyboard snippet chambers",
        "```",
        "",
        "### Python API",
        "",
        "```python",
        "from copyboard_extension.agent_api import (",
        "    get_profile, fire_snippet, search_snippets,",
        "    get_chambers, add_snippet, get_board,",
        ")",
        "",
        "profile = get_profile()       # coding fingerprint",
        "result = fire_snippet(0, 2)   # fire a specific snippet",
        'hits = search_snippets("docker")  # search',
        "```",
        "",
        "### MCP Server",
        "",
        "If configured, agents can use the Copyboard MCP server:",
        "",
        "```json",
        '{',
        '  "mcpServers": {',
        '    "copyboard": {',
        '      "command": "python",',
        '      "args": ["-m", "copyboard_extension.mcp_server"]',
        '    }',
        '  }',
        '}',
        "```",
        "",
    ])

    content = "\n".join(lines)

    filepath = os.path.join(output_dir, filename)
    try:
        with open(filepath, "w") as f:
            f.write(content)
    except (IOError, OSError) as e:
        print(f"Error writing context file: {e}")
        return ""

    return filepath
