name: copyboard_mobile
description: Ten-chamber mobile clipboard revolver with native cross-app drag
version: 0.2.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  super_drag_and_drop: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
